name: Upload docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: { }

concurrency:
  group: holoinsight-agent-upload-docker-image
  cancel-in-progress: true

jobs:
  upload-docker-image:
    runs-on: ubuntu-latest
    if: github.repository == 'traas-stack/holoinsight-agent'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Upload HoloInsight Agent Docker Image
      shell: bash
      run: |
        docker buildx create --use
        ./scripts/gen-git-info.sh
        tag=latest ./scripts/docker/buildx.sh
